# coding=utf-8
# *** WARNING: this file was generated by pulumi-gen-awslbcontroller. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "namespace_id": "namespaceId",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "namespaceId": "namespace_id",
}
