# coding=utf-8
# *** WARNING: this file was generated by pulumi-gen-awslbcontroller. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "create_namespace": "createNamespace",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "createNamespace": "create_namespace",
}
